// Code generated by mockery v2.42.2. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto_gen "order/proto_gen/internal_proto"
)

// ProductServiceClient is an autogenerated mock type for the ProductServiceClient type
type ProductServiceClient struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) CreateProduct(ctx context.Context, in *proto_gen.CreateProductRequest, opts ...grpc.CallOption) (*proto_gen.CreateProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *proto_gen.CreateProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto_gen.CreateProductRequest, ...grpc.CallOption) (*proto_gen.CreateProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto_gen.CreateProductRequest, ...grpc.CallOption) *proto_gen.CreateProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto_gen.CreateProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto_gen.CreateProductRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProduct provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) GetProduct(ctx context.Context, in *proto_gen.GetProductRequest, opts ...grpc.CallOption) (*proto_gen.GetProductResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *proto_gen.GetProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto_gen.GetProductRequest, ...grpc.CallOption) (*proto_gen.GetProductResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto_gen.GetProductRequest, ...grpc.CallOption) *proto_gen.GetProductResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto_gen.GetProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto_gen.GetProductRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProducts provides a mock function with given fields: ctx, in, opts
func (_m *ProductServiceClient) GetProducts(ctx context.Context, in *proto_gen.GetProductsRequest, opts ...grpc.CallOption) (*proto_gen.GetProductsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetProducts")
	}

	var r0 *proto_gen.GetProductsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto_gen.GetProductsRequest, ...grpc.CallOption) (*proto_gen.GetProductsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto_gen.GetProductsRequest, ...grpc.CallOption) *proto_gen.GetProductsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto_gen.GetProductsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto_gen.GetProductsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductServiceClient creates a new instance of ProductServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductServiceClient {
	mock := &ProductServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
