// Code generated by mockery v2.42.2. DO NOT EDIT.

package proto_gen

import mock "github.com/stretchr/testify/mock"

// MockUnsafeProductServiceServer is an autogenerated mock type for the UnsafeProductServiceServer type
type MockUnsafeProductServiceServer struct {
	mock.Mock
}

type MockUnsafeProductServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeProductServiceServer) EXPECT() *MockUnsafeProductServiceServer_Expecter {
	return &MockUnsafeProductServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedProductServiceServer provides a mock function with given fields:
func (_m *MockUnsafeProductServiceServer) mustEmbedUnimplementedProductServiceServer() {
	_m.Called()
}

// MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedProductServiceServer'
type MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedProductServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeProductServiceServer_Expecter) mustEmbedUnimplementedProductServiceServer() *MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	return &MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedProductServiceServer")}
}

func (_c *MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call) Run(run func()) *MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call) Return() *MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call) RunAndReturn(run func()) *MockUnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnsafeProductServiceServer creates a new instance of MockUnsafeProductServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeProductServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeProductServiceServer {
	mock := &MockUnsafeProductServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
