// Code generated by mockery v2.42.2. DO NOT EDIT.

package proto_gen

import mock "github.com/stretchr/testify/mock"

// MockUnsafeOrderServiceServer is an autogenerated mock type for the UnsafeOrderServiceServer type
type MockUnsafeOrderServiceServer struct {
	mock.Mock
}

type MockUnsafeOrderServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeOrderServiceServer) EXPECT() *MockUnsafeOrderServiceServer_Expecter {
	return &MockUnsafeOrderServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedOrderServiceServer provides a mock function with given fields:
func (_m *MockUnsafeOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	_m.Called()
}

// MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedOrderServiceServer'
type MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedOrderServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeOrderServiceServer_Expecter) mustEmbedUnimplementedOrderServiceServer() *MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call {
	return &MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedOrderServiceServer")}
}

func (_c *MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call) Run(run func()) *MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call) Return() *MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call) RunAndReturn(run func()) *MockUnsafeOrderServiceServer_mustEmbedUnimplementedOrderServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUnsafeOrderServiceServer creates a new instance of MockUnsafeOrderServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeOrderServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeOrderServiceServer {
	mock := &MockUnsafeOrderServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
