// Code generated by mockery v2.42.2. DO NOT EDIT.

package proto_gen

import mock "github.com/stretchr/testify/mock"

// UnsafeProductServiceServer is an autogenerated mock type for the UnsafeProductServiceServer type
type UnsafeProductServiceServer struct {
	mock.Mock
}

type UnsafeProductServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *UnsafeProductServiceServer) EXPECT() *UnsafeProductServiceServer_Expecter {
	return &UnsafeProductServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedProductServiceServer provides a mock function with given fields:
func (_m *UnsafeProductServiceServer) mustEmbedUnimplementedProductServiceServer() {
	_m.Called()
}

// UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedProductServiceServer'
type UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedProductServiceServer is a helper method to define mock.On call
func (_e *UnsafeProductServiceServer_Expecter) mustEmbedUnimplementedProductServiceServer() *UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	return &UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedProductServiceServer")}
}

func (_c *UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call) Run(run func()) *UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call) Return() *UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call) RunAndReturn(run func()) *UnsafeProductServiceServer_mustEmbedUnimplementedProductServiceServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewUnsafeProductServiceServer creates a new instance of UnsafeProductServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeProductServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeProductServiceServer {
	mock := &UnsafeProductServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
