// Code generated by mockery v2.42.2. DO NOT EDIT.

package ports

import (
	context "context"
	domains "product_order/internal/application/core/domains"

	mock "github.com/stretchr/testify/mock"
)

// OrderPort is an autogenerated mock type for the OrderPort type
type OrderPort struct {
	mock.Mock
}

type OrderPort_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderPort) EXPECT() *OrderPort_Expecter {
	return &OrderPort_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, id
func (_m *OrderPort) GetOrder(ctx context.Context, id int32) (domains.Order, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 domains.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (domains.Order, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) domains.Order); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domains.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderPort_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderPort_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *OrderPort_Expecter) GetOrder(ctx interface{}, id interface{}) *OrderPort_GetOrder_Call {
	return &OrderPort_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, id)}
}

func (_c *OrderPort_GetOrder_Call) Run(run func(ctx context.Context, id int32)) *OrderPort_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *OrderPort_GetOrder_Call) Return(_a0 domains.Order, _a1 error) *OrderPort_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderPort_GetOrder_Call) RunAndReturn(run func(context.Context, int32) (domains.Order, error)) *OrderPort_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderPort creates a new instance of OrderPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderPort {
	mock := &OrderPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
