// Code generated by mockery v2.42.2. DO NOT EDIT.

package ports

import (
	context "context"
	domains "product_order/internal/application/core/domains"

	mock "github.com/stretchr/testify/mock"
)

// ProductPort is an autogenerated mock type for the ProductPort type
type ProductPort struct {
	mock.Mock
}

type ProductPort_Expecter struct {
	mock *mock.Mock
}

func (_m *ProductPort) EXPECT() *ProductPort_Expecter {
	return &ProductPort_Expecter{mock: &_m.Mock}
}

// GetProduct provides a mock function with given fields: ctx, id
func (_m *ProductPort) GetProduct(ctx context.Context, id int32) (domains.Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 domains.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int32) (domains.Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int32) domains.Product); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domains.Product)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int32) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductPort_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type ProductPort_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - id int32
func (_e *ProductPort_Expecter) GetProduct(ctx interface{}, id interface{}) *ProductPort_GetProduct_Call {
	return &ProductPort_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, id)}
}

func (_c *ProductPort_GetProduct_Call) Run(run func(ctx context.Context, id int32)) *ProductPort_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int32))
	})
	return _c
}

func (_c *ProductPort_GetProduct_Call) Return(_a0 domains.Product, _a1 error) *ProductPort_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ProductPort_GetProduct_Call) RunAndReturn(run func(context.Context, int32) (domains.Product, error)) *ProductPort_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewProductPort creates a new instance of ProductPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductPort {
	mock := &ProductPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
