# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Product_microservice

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create docker network
        run: docker network create store
      - name: run docker compose
        run: docker-compose -f product/docker-compose.yml up -d

  