# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Project

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create docker network
        run: docker network create store
      - name: run make file
        run: make run

